# Generated by Django 2.2.16 on 2022-10-22 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221022_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message=' Должно состоять из латинских букв и цифр', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
