# Generated by Django 2.2.16 on 2022-10-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20221023_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingradients',
            new_name='ingredients',
        ),
    ]
