# Generated by Django 4.1.3 on 2022-11-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0002_auto_20221030_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyToken',
            fields=[
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authtoken.tokenproxy',),
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
