# Generated by Django 2.2.16 on 2022-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_auto_20221028_0343'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='isinshoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'is_in_shopping_cart'), name='unique_user_is_in_shopping_cart'),
        ),
    ]
