# Generated by Django 4.1.3 on 2022-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_isinshoppingcart_is_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isinshoppingcart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
